// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Character is created by the user
 * to represent a actor that can
 * interact in dialogs.
 * Character has a mandatory name, and
 * can have a description, a portrait,
 * a general artwork and a background image.
 * It is always linked to a project and it's
 * stats
 */
export type Character = { id: string, display_name: string, first_name: string | null, last_name: string | null, description: string | null, portrait_link: string | null, artwork_link: string | null, background_link: string | null, };
