// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CharacterVariable = { id: string, name: string, current_state: string, potential_states: Array<string>, character_id: string, };
