// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CharacterForm represents the form a user can fill
 * to create a new user
 */
export type CharacterForm = { id: string, display_name: string, first_name: string | null, last_name: string | null, description: string | null, };
