// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimpleCharacter } from "./SimpleCharacter";

export type CharacterMetadata = { data: { [key in string]?: SimpleCharacter }, };
