// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";
import type { CommitInfo } from "./CommitInfo";

export type CommitGraph = { commits: Array<CommitInfo>, head: string | null, branches: Array<BranchInfo>, };
