// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitInfo = { id: string, message: string | null, author: string | null, email: string | null, timestamp: bigint, parents: Array<string>, };
