// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NecessityExpression } from "./NecessityExpression";

export type Conditions = { priority: number, necessities: Array<NecessityExpression>, next_node: string | null, };
