// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DialogNode = { next_node: string | null, character_id: string | null, content_link: string | null, content: string | null, };
