// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimpleDialog } from "./SimpleDialog";

export type DialogMetadata = { data: { [key in string]?: SimpleDialog }, };
