// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

export type Dialog = { id: string, name: string, root_node: string | null, characters_ids: Array<string>, created_at: string, main_character: string, nodes: { [key in string]?: Node }, };
