// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterVariableState } from "./CharacterVariableState";

export type GlobalCharacterVariable = { id: string, name: string, potential_states: Array<string>, characters: Array<CharacterVariableState>, };

