// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeNecessity } from "./TreeNecessity";
import type { VarNecessity } from "./VarNecessity";

export type NecessityExpression = { "Tree": TreeNecessity } | { "Var": VarNecessity };
