// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choices } from "./Choices";
import type { DialogNode } from "./DialogNode";
import type { Phylum } from "./Phylum";

export type NodeData = { "Dialog": DialogNode } | { "Phylum": Phylum } | { "Choices": Choices };
