// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeData } from "./NodeData";

export type Node = { pos_x: number, pos_y: number, data: NodeData, };
