// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conditions } from "./Conditions";

export type Phylum = { id: string, name: string | null, branches: Array<Conditions>, };
