// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectMetadata } from "./ProjectMetadata";

export type Project = { id: string, name: string, path: string, metadata: ProjectMetadata, };
