// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectMetadata = { created_at: string, last_commit: string | null, current_branch: string | null, branches: Array<string>, };
