// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimpleDialog = { id: string, name: string, main_character: string, characters: Array<string>, };
