// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NecessityExpression } from "./NecessityExpression";
import type { Operator } from "./Operator";

export type TreeNecessity = { left: NecessityExpression, operator: Operator, right: NecessityExpression, };
