// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Variable } from "./Variable";

export type VariableStore = { data: Array<Variable>, };
