// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterVariable } from "./CharacterVariable";
import type { DialogVariable } from "./DialogVariable";
import type { GlobalCharacterVariable } from "./GlobalCharacterVariable";
import type { GlobalVariable } from "./GlobalVariable";

export type Variable = { "Global": GlobalVariable } | { "GlobalChar": GlobalCharacterVariable } | { "Char": CharacterVariable } | { "Dialog": DialogVariable };
